[package]
name = "mmd-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Millions Must Die engine library"
publish = false

[dependencies]
hex.workspace = true
ron.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true
sha2.workspace = true
tempfile.workspace = true
